/*jslint node: true, nomen: true */
"use strict";

var ko = require('knockout');

exports.register = function () {
    require('./main-application').register();
    require('./c-log-in').register();
    require('./c-master').register();
    require('./c-sign-up').register();
    require('./c-worker-container').register();
    require('./c-xor-log-in').register();
    require('./c-master-box').register();
    require('./c-manage-workers-modal').register();
    require('./c-images-waiting-modal-container').register();
    require('./c-statistics-modal').register();
    require('./c-edit-campaign-modal').register();
    require('./c-sign-up-form').register();
    require('./c-worker-box').register();
    require('./c-log-in-form-container').register();
    require('./c-welcome-to-user').register();
    require('./c-master-basic-information-container').register();
    require('./c-master-edit-account').register();
    require('./c-master-create-campaign-container').register();
    require('./c-master-edit-campaigns-container').register();
    require('./c-modal-worker-list').register();
    require('./c-modal-images-list').register();
    require('./c-statistics-in-numbers').register();
    require('./c-images-statistics-list').register();
    require('./c-edit-campaign-form').register();
    require('./c-worker-basic-information-container').register();
    require('./c-worker-edit-account').register();
    require('./c-worker-edit-tasks').register();
    require('./c-log-in-form').register();
    require('./c-master-basic-information-details').register();
    require('./c-edit-account-form').register();
    require('./c-account-info-details').register();
    require('./c-master-create-campaign-form').register();
    require('./c-master-waiting-campaigns-container').register();
    require('./c-master-running-campaigns-container').register();
    require('./c-master-ended-campaigns-container').register();
    require('./c-worker-basic-information-details').register();
    require('./c-account-info-details-worker').register();
    require('./c-worker-account-form').register();
    require('./c-master-waiting-campaign-list-container').register();
    require('./c-master-waiting-campaign-selected-container').register();
    require('./c-master-running-campaign-list-container').register();
    require('./c-master-running-campaign-selected-container').register();
    require('./c-master-ended-campaign-list-container').register();
    require('./c-master-ended-campaign-selected-container').register();
    require('./c-master-waiting-campaigns-list').register();
    require('./c-master-selected-waiting-campaign-details').register();
    require('./c-master-running-campaigns-list').register();
    require('./c-master-selected-running-campaign-details').register();
    require('./c-master-ended-campaigns-list').register();
    require('./c-master-selected-ended-campaign-details').register();
    require('./c-task-control-container').register();
    require('./c-information-or-image-container').register();
    require('./c-task-statistics-container').register();
    require('./c-worker-selected-statistics-task-details').register();
    require('./c-worker-tasks-container').register();
    require('./c-worker-tasks-list').register();
    require('./c-worker-task-command-container').register();
    require('./c-line-drawer').register();
};
